In [1]:
def divisible(numerator, denominator):
    try:
        ans = numerator/ denominator
        print(ans)
    except Exception as e:
        
        if denominator == 0:
            
            raise ArithmeticError("denominator cannot be zero")
    

In [2]:
divisible(4,5)

0.8


In [3]:
divisible(5,0)

ArithmeticError: denominator cannot be zero

In [4]:
subjects=["Americans","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

for i in subjects:
    for j in verbs:
        for k in objects:
            print(i +' '+ j +' '+ k)

Americans play Baseball
Americans play Cricket
Americans watch Baseball
Americans watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


In [5]:
def matrixx(iterable,N, increasing= False):
    vanmat= []
    for j in range(0,N):
        for index, value in enumerate(iterable):
            
            if increasing == False:
                
            
                if j==0:
                    vanmat.append(1)
                else:
                    vanmat.append(value**j)
            if increasing == True:
                
                if j==N-1:
                    vanmat.append(1)
                else:
                    vanmat.append(value**(N-j-1))
                
    import numpy as np
    vanmat= np.reshape(vanmat, (N,len(iterable)))
    return vanmat            

In [7]:
list1 = [2,4,6,8]

In [8]:
list3 = matrixx(list1,3,True)

In [9]:
print(list3)

[[ 4 16 36 64]
 [ 2  4  6  8]
 [ 1  1  1  1]]


In [10]:
list2 = matrixx(list1,3)

In [11]:
print(list2)

[[ 1  1  1  1]
 [ 2  4  6  8]
 [ 4 16 36 64]]
